//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Player/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""b51d8ec8-ea6e-4138-ba8d-ebd92c9cdd89"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d09d3345-405b-4981-b6d4-53d64eeb51dc"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": ""NormalizeVector3"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a56efb86-f143-438a-9fcd-34f8746b3af9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""e8ed4d7e-e199-45d5-9683-4b7c3d4b2589"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.5)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7730abd8-a866-488b-8657-161ace2b1939"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hide"",
                    ""type"": ""Button"",
                    ""id"": ""adf60f75-31ca-475c-bfc5-efdad7221c25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemSwap"",
                    ""type"": ""Button"",
                    ""id"": ""e746beba-5da3-4771-9735-ccf978e07f49"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OffOn"",
                    ""type"": ""Button"",
                    ""id"": ""12afe2fa-73b0-42b7-875a-a1059f3530ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OffOnHeld"",
                    ""type"": ""Button"",
                    ""id"": ""b3142366-26b1-48ad-8271-f8d37ddaa84a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=5)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""e1fed016-48d5-4059-a047-944fde4c2ad1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeldInteract"",
                    ""type"": ""Button"",
                    ""id"": ""6a62a3fb-5632-4762-b7c7-395db6f161d7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=10,pressPoint=0.1)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Defrost"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c6b7373b-2825-47a1-bc1c-cba3b3189dda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=5)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenAndCloseInv"",
                    ""type"": ""Button"",
                    ""id"": ""5a7b1ae5-ce36-4911-9894-5897ee776bfb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""3372bad4-dd91-48a7-a20d-a524fa2fc909"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""1e6d745e-8aab-408b-92bc-5ea03b791d96"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""de7c63cc-5644-4ecf-ac75-ad9a63bbb6ad"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4e4bdf4d-549d-4cd3-b3a0-e4d960c3f3aa"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3fe69202-8dc7-4f87-9589-3d992e68ef97"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b03ef68-ba77-4ce9-b886-448271e3c800"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""9fa0222d-e4a7-4b03-8d80-cab154c26df3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""fa31926a-ee4c-4944-af45-f22492315781"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""216b7692-8f13-4fa0-8504-cf06b498917a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18b2a0cd-3c3d-4196-9cb1-c7caad6e5e93"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c3e994f-ec4e-4771-b93e-741f9077ee6b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d5a9d1f-ff65-4360-81e4-cf0d0de60abf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5089a965-8a00-45a7-88c2-26c62b61e6e8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71b1c2a3-dc02-4376-8c79-7fda1882839f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeldInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1654f0b7-b7dc-453e-9ee3-eb164a21438d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""ItemSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a9c0cc4-f666-4d3c-bc98-1cdc5c328c56"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""ItemSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a62568-22a8-4273-afbe-fb9eed8e0794"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""ItemSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67118350-7d4d-43a3-b485-fb22580802bc"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""ItemSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb5a0262-77b9-4b26-b8fd-8dcff1afe06e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=5)"",
                    ""groups"": """",
                    ""action"": ""ItemSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1359a0c1-15c2-4d54-af19-3a18a2af7dc6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OffOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9d78b49-4bc0-4118-ba36-0160446a65ab"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OffOnHeld"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35b7bb0c-a3a3-4d54-ad51-b2488582e9c5"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenAndCloseInv"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82ba7219-38d4-4602-be76-c7ba10365dae"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Defrost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eb925a2-eeaf-4355-bcce-83dd4ac4fd3a"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Movement = m_InGame.FindAction("Movement", throwIfNotFound: true);
        m_InGame_Mouse = m_InGame.FindAction("Mouse", throwIfNotFound: true);
        m_InGame_Sprint = m_InGame.FindAction("Sprint", throwIfNotFound: true);
        m_InGame_MousePos = m_InGame.FindAction("MousePos", throwIfNotFound: true);
        m_InGame_Hide = m_InGame.FindAction("Hide", throwIfNotFound: true);
        m_InGame_ItemSwap = m_InGame.FindAction("ItemSwap", throwIfNotFound: true);
        m_InGame_OffOn = m_InGame.FindAction("OffOn", throwIfNotFound: true);
        m_InGame_OffOnHeld = m_InGame.FindAction("OffOnHeld", throwIfNotFound: true);
        m_InGame_Interact = m_InGame.FindAction("Interact", throwIfNotFound: true);
        m_InGame_HeldInteract = m_InGame.FindAction("HeldInteract", throwIfNotFound: true);
        m_InGame_Defrost = m_InGame.FindAction("Defrost", throwIfNotFound: true);
        m_InGame_OpenAndCloseInv = m_InGame.FindAction("OpenAndCloseInv", throwIfNotFound: true);
        m_InGame_MainMenu = m_InGame.FindAction("MainMenu", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_InGame.enabled, "This will cause a leak and performance issues, Controls.InGame.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Movement;
    private readonly InputAction m_InGame_Mouse;
    private readonly InputAction m_InGame_Sprint;
    private readonly InputAction m_InGame_MousePos;
    private readonly InputAction m_InGame_Hide;
    private readonly InputAction m_InGame_ItemSwap;
    private readonly InputAction m_InGame_OffOn;
    private readonly InputAction m_InGame_OffOnHeld;
    private readonly InputAction m_InGame_Interact;
    private readonly InputAction m_InGame_HeldInteract;
    private readonly InputAction m_InGame_Defrost;
    private readonly InputAction m_InGame_OpenAndCloseInv;
    private readonly InputAction m_InGame_MainMenu;
    public struct InGameActions
    {
        private @Controls m_Wrapper;
        public InGameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_InGame_Movement;
        public InputAction @Mouse => m_Wrapper.m_InGame_Mouse;
        public InputAction @Sprint => m_Wrapper.m_InGame_Sprint;
        public InputAction @MousePos => m_Wrapper.m_InGame_MousePos;
        public InputAction @Hide => m_Wrapper.m_InGame_Hide;
        public InputAction @ItemSwap => m_Wrapper.m_InGame_ItemSwap;
        public InputAction @OffOn => m_Wrapper.m_InGame_OffOn;
        public InputAction @OffOnHeld => m_Wrapper.m_InGame_OffOnHeld;
        public InputAction @Interact => m_Wrapper.m_InGame_Interact;
        public InputAction @HeldInteract => m_Wrapper.m_InGame_HeldInteract;
        public InputAction @Defrost => m_Wrapper.m_InGame_Defrost;
        public InputAction @OpenAndCloseInv => m_Wrapper.m_InGame_OpenAndCloseInv;
        public InputAction @MainMenu => m_Wrapper.m_InGame_MainMenu;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
            @Hide.started += instance.OnHide;
            @Hide.performed += instance.OnHide;
            @Hide.canceled += instance.OnHide;
            @ItemSwap.started += instance.OnItemSwap;
            @ItemSwap.performed += instance.OnItemSwap;
            @ItemSwap.canceled += instance.OnItemSwap;
            @OffOn.started += instance.OnOffOn;
            @OffOn.performed += instance.OnOffOn;
            @OffOn.canceled += instance.OnOffOn;
            @OffOnHeld.started += instance.OnOffOnHeld;
            @OffOnHeld.performed += instance.OnOffOnHeld;
            @OffOnHeld.canceled += instance.OnOffOnHeld;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @HeldInteract.started += instance.OnHeldInteract;
            @HeldInteract.performed += instance.OnHeldInteract;
            @HeldInteract.canceled += instance.OnHeldInteract;
            @Defrost.started += instance.OnDefrost;
            @Defrost.performed += instance.OnDefrost;
            @Defrost.canceled += instance.OnDefrost;
            @OpenAndCloseInv.started += instance.OnOpenAndCloseInv;
            @OpenAndCloseInv.performed += instance.OnOpenAndCloseInv;
            @OpenAndCloseInv.canceled += instance.OnOpenAndCloseInv;
            @MainMenu.started += instance.OnMainMenu;
            @MainMenu.performed += instance.OnMainMenu;
            @MainMenu.canceled += instance.OnMainMenu;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
            @Hide.started -= instance.OnHide;
            @Hide.performed -= instance.OnHide;
            @Hide.canceled -= instance.OnHide;
            @ItemSwap.started -= instance.OnItemSwap;
            @ItemSwap.performed -= instance.OnItemSwap;
            @ItemSwap.canceled -= instance.OnItemSwap;
            @OffOn.started -= instance.OnOffOn;
            @OffOn.performed -= instance.OnOffOn;
            @OffOn.canceled -= instance.OnOffOn;
            @OffOnHeld.started -= instance.OnOffOnHeld;
            @OffOnHeld.performed -= instance.OnOffOnHeld;
            @OffOnHeld.canceled -= instance.OnOffOnHeld;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @HeldInteract.started -= instance.OnHeldInteract;
            @HeldInteract.performed -= instance.OnHeldInteract;
            @HeldInteract.canceled -= instance.OnHeldInteract;
            @Defrost.started -= instance.OnDefrost;
            @Defrost.performed -= instance.OnDefrost;
            @Defrost.canceled -= instance.OnDefrost;
            @OpenAndCloseInv.started -= instance.OnOpenAndCloseInv;
            @OpenAndCloseInv.performed -= instance.OnOpenAndCloseInv;
            @OpenAndCloseInv.canceled -= instance.OnOpenAndCloseInv;
            @MainMenu.started -= instance.OnMainMenu;
            @MainMenu.performed -= instance.OnMainMenu;
            @MainMenu.canceled -= instance.OnMainMenu;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnHide(InputAction.CallbackContext context);
        void OnItemSwap(InputAction.CallbackContext context);
        void OnOffOn(InputAction.CallbackContext context);
        void OnOffOnHeld(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnHeldInteract(InputAction.CallbackContext context);
        void OnDefrost(InputAction.CallbackContext context);
        void OnOpenAndCloseInv(InputAction.CallbackContext context);
        void OnMainMenu(InputAction.CallbackContext context);
    }
}
